# Site settings
title: HoangNT Blog
email: hoangnt@me.com
description: "A little bit corner of my mind"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: MiraMera Inc.
  location: Hanoi - Vietnam
  social: Infinity and beyond
  credits: Jekyll and Freelancer Theme

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/mirameka
  - title: facebook
    url: http://facebook.com/mirameka
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/mirameka
  - title: bitbucket 
    url: http://bitbucket.org/mirameka
  - title: github
    url: http://github.com/mirameka

# Postal address (add as many lines as necessary)
address:
  - line: 48 Bach Mai Street
  - line: Hanoi 10000, Vietnam
  
# Credits content
credits: ''

# Build settings
markdown: kramdown
permalink: pretty
