# Site settings
title: "Hoang NT"
email: hoangnt@ai.cs.titech.ac.jp
description: "Everything should be explained easily"
baseurl: 
url:  
title_description: "\"If you can't explain it, you don't understand it well enough\" - Albert Einstein. My blog is a place where I explain everything I have learned as simple as I can, so that anyone, including my future self, can understand."
title_image: "./images/hoang-bio-photo.png"
google_analytics: "UA-69058925-1"
disqus_account: hoangnt 
github_repository: https://github.com/gear/
addthis_id: 
post_limit: 10

# Social usernames/URLs
twitter_username: 
github_username: gear 
linkedin_link: jp.linkedin.com/in/hoang-nguyen-788035b5
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: "By Hoang Nguyen with theme from <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "prettify"]
permalink: pretty
exclude: [vendor]
